// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV8XXBVGOEAcf8r2Cfh5kCLettY7547ic',
    appId: '1:132616724746:web:343c2c4190fa266f3fdaf3',
    messagingSenderId: '132616724746',
    projectId: 'dwit-project',
    authDomain: 'dwit-project.firebaseapp.com',
    storageBucket: 'dwit-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQTgYs03EqBgTe-eQYAagVYMSm-pUNr8I',
    appId: '1:132616724746:android:351d08db5b51c94d3fdaf3',
    messagingSenderId: '132616724746',
    projectId: 'dwit-project',
    storageBucket: 'dwit-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4asQbeZ8hv399mCGnF_wcB7VThnXu1Qc',
    appId: '1:132616724746:ios:1ae652eedb9333153fdaf3',
    messagingSenderId: '132616724746',
    projectId: 'dwit-project',
    storageBucket: 'dwit-project.appspot.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4asQbeZ8hv399mCGnF_wcB7VThnXu1Qc',
    appId: '1:132616724746:ios:1ae652eedb9333153fdaf3',
    messagingSenderId: '132616724746',
    projectId: 'dwit-project',
    storageBucket: 'dwit-project.appspot.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV8XXBVGOEAcf8r2Cfh5kCLettY7547ic',
    appId: '1:132616724746:web:3ca8ea34a35e1e573fdaf3',
    messagingSenderId: '132616724746',
    projectId: 'dwit-project',
    authDomain: 'dwit-project.firebaseapp.com',
    storageBucket: 'dwit-project.appspot.com',
  );
}
